---
root: true
extends: eslint:recommended
env:
  es6: true
  mocha: true
  node: true
parserOptions:
  ecmaVersion: 2018
rules:
  indent: [error, 4]
  no-console: off
  no-var: error
  prefer-const: warn
